version: '3.8'
services:
  web:
    build: .
    container_name: ai-jobbot-web
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    container_name: ai-jobbot-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ai_jobbot
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: ai-jobbot-redis
    restart: always

volumes:
  db_data:
